windingwind/zotero-pdf-translate

- src/dict/youdaodict.ts
- src/translate.ts
> feat: word definition for EN-to-CN translation

- src/translate/google.ts
Change client from webapp to gtx. It seems to have better accuracy...
> opt: Change client of Google APIs

- addon/chrome/content/preferences.xul
- addon/chrome/locale/en-US/overlay.dtd
- addon/chrome/locale/zh-CN/overlay.dtd
- src/config.ts
- src/dict/collins.ts
- src/locale.ts
- src/translate.ts
> add: collins dict

- src/locale.ts
在请求错误的中文提示里，将原来的 issue 地址替换为语雀文档地址
> add: yuque doc link in error_request

- addon/chrome/content/preferences.xul
- addon/chrome/locale/en-US/overlay.dtd
- addon/chrome/locale/zh-CN/overlay.dtd
- package.json
- src/addon.ts
- src/dict/bingdict.ts
- src/dict/collins.ts
- src/translate.ts
- src/view.ts
> Add: New feature to play audio of a word in dictionary.

- src/translate/tencent.ts
Trying to remove dependency `crypto-js` (replaced by build-in [`crypto` api](https://developer.mozilla.org/en-US/docs/Web/API/Crypto))
> refactor: use build-in crypto api for tencent api

- src/base.ts
- src/dict/bingdict.ts
- src/dict/collins.ts
- src/dict/weblio.ts
add `str2dom` function to parse document from string
> fix bing mp3

- src/view.ts
目前是拖动过程中，popup不会随textbox缩短，mouseup后才变。
> fix popup height when resize

- src/modules/services/gpt.ts
refine gpt prompt by ChatGPT plugin "Prompt Perfect", solve #466
> fix: refine gpt prompt

- src/modules/services/cnki.ts
#518 
CNKI 真的是。。。几天不见居然就把广告更新了。
> fix: cnki 更新广告模板后无法正常清理

- README.md
- addon/locale/en-US/addon.ftl
- addon/locale/zh-CN/addon.ftl
- src/modules/services/aliyun.ts
- src/modules/services/index.ts
- src/utils/config.ts
- src/utils/crypto.ts
Fixes: #497.
Testing steps:
1. Create AK, SK in [ram console](https://ram.console.aliyun.com/manage/ak).
2. And subscribe to the [general translation service](https://www.aliyun.com/product/ai/alimt).
3. Set up accessKeyId and accessKeySecret in settings.
I've tested this locally:
> feat: support ali translate API

- src/modules/menu.ts
貌似没有favicon@0.5x.png资源，修改为favicon.png
> fix: menu icon don't display

- src/modules/services/deepl.ts
> 新增第三方Deepl Api接口

- addon/locale/en-US/addon.ftl
- addon/locale/zh-CN/addon.ftl
- src/modules/settings/gpt.ts
为了减少后续代码的修改，APIVersion 也成为可变参数
> 之前的 PR 漏掉了
> update: azureGPT add APIVserion

- README.md
- addon/locale/en-US/addon.ftl
- addon/locale/it-IT/addon.ftl
- addon/locale/zh-CN/addon.ftl
- addon/prefs.js
- src/modules/popup.ts
- src/modules/reader.ts
- src/modules/services/gemini.ts
- src/modules/services/index.ts
- src/modules/settings/gemini.ts
- src/modules/settings/index.ts
- src/utils/config.ts
增加Gemini API，如有需要后续可补充帮助Gist
使用时需保证访问Gemini的IP为受支持的地区，如美国、新加坡。（所有支持地区可在此查看：https://ai.google.dev/available_regions#available_regions ）
目前API使用暂时免费，可在此申请：https://ai.google.dev/tutorials/setup
> Add Gemini API

- .github/dependabot.yml
add "github-actions" [package ecosystem](https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
> ci(dependabot): add "github-actions" package ecosystem

- src/modules/services/bingdict.ts
Fix the bug that Bing dictionary cannot play pronunciation
> Fix the bug that Bing dictionary cannot play pronunciation

- src/modules/services/microsoft.ts
- src/utils/config.ts
fixed #1004
update preference prompt for the Microsoft translator.
> fix: add region to microsoft translator api

- addon/prefs.js
Remove duplicate 'translation'
> chore: fix typo

- src/modules/services/bingdict.ts
> fix: bing dictionary pronunciation

- README.md
- After [#1066](https://github.com/windingwind/zotero-pdf-translate/pull/1066)
> doc: regression for faq in readme

- package-lock.json
- src/modules/shortcuts.ts
> fix: ensure shortcuts work when tab is moved to separate window

- README.md
- addon/locale/en-US/panel.ftl
- addon/locale/it-IT/panel.ftl
- addon/locale/it-IT/preferences.ftl
- addon/locale/zh-CN/panel.ftl
- v2.2.0之后，修改locale string，Alt-->Ctrl （for Windows/Linux）
> fix: update ctrl locale string for concat mode

- src/modules/settings/qwenmt.ts
> fix: config pane can not be opened, re #1115

- addon/chrome/content/preferences.xhtml
- addon/locale/en-US/preferences.ftl
- addon/locale/it-IT/preferences.ftl
- addon/locale/zh-CN/preferences.ftl
- 调整Interface与Services两groupbox间的段落间距
- 调整Services的排布顺序，并更新play的locale string，添加发音播放icon🔊，提示用户播放 checkbox与单词服务带🔊的Service相关
> chore: refactor setting layout

- addon/locale/en-US/addon.ftl
- addon/locale/it-IT/addon.ftl
- addon/locale/zh-CN/addon.ftl
- src/modules/reader.ts
- src/modules/settings/claude.ts
- src/modules/settings/gpt.ts
- typings/i10n.d.ts
> add tooltip for the icon in sidebar

- src/utils/config.ts
re https://github.com/windingwind/zotero-pdf-translate/issues/1221#issuecomment-3063456710
> fix: incorrect alert for the microsoft secert with #region

- addon/chrome/content/styles/panel.css
- addon/prefs.js
- src/elements/panel.ts
- src/modules/tabpanel.ts
- typings/prefs.d.ts
- Keep the minimum height limited to 100px.
> add: make text area in panel adjustable, closes #1220

- src/modules/services/aliyun.ts
- src/modules/services/qwenmt.ts
Resolve https://github.com/windingwind/zotero-pdf-translate/pull/1115#issuecomment-2727870148
> feat: add nonStream hint and support more zh-Hant locales
