windingwind/zotero-pdf-translate

addon/chrome/content/preferences.xul, addon/chrome/locale/en-US/overlay.dtd, addon/chrome/locale/zh-CN/overlay.dtd, src/config.ts, src/dict/freedictionaryapi.ts, src/events.ts, src/translate.ts
Add dictionary engine for en-en
Dictionary is useful for English when reading more complex texts. This PR adds dictionary from "Free Dictionary API".
=> Add dictionary engine for en-en

src/translate/youdaozhiyun.ts
continue #299.
[`String.padStart` is supported by `firefox 60`](https://caniuse.com/?search=padstart) which is the platform of Zotero.
=> refactor: use build-in crypto api for youdaozhiyun api

package.json, src/translate/cnki.ts, src/translate/crypto.ts, src/translate/niutrans.ts, src/translate/tencent.ts, src/translate/xftrans.ts, src/translate/youdao.ts, src/translate/youdaozhiyun.ts
I've use [AES CBC](https://developer.mozilla.org/zh-CN/docs/Web/API/SubtleCrypto/encrypt#aes-cbc_2) mode (which is supported by web crypto API) to simulate AES ECB (which is not supported). And now, we can remove package `crypto-js`.
build: move `compressing`, `esbuild`, and `replace-in-file` to devdependencies.
After refactoring, the size of `.xpi` file reduced to `62.9KB` (from `86KB`)
Note: I haven't tested [`xftrans`](https://www.xfyun.cn/services/xftrans). The logic just seems ok for me.
=> refactor: remove `crypto-js` and extract crypto helper function to a single module

src/modules/services/bingdict.ts
Since the phonetic has already in tool-button, they should be excluded from the description. 
As far as I know, there is no longer needed to loop of the lines, I just keep the code there for robustness.
=> fix bing phonetic

README.md, package.json, src/addon.ts, src/hooks.ts, src/modules/prompt.ts
```display mode: column```
```display mode: row```
#300 
This feature is very convenient for viewing large passages of text in their original translations.
There is a basic assumption: the translation engine does not split a sentence into multiple translations. The number of sentences in the original translation is the same.
This function is based on **manual sentence segmentation**, so it works with **all translation engines**. 
Currently, **only** English to Chinese translation is supported. 
So I have added the following restrictions so that mismatched translation configurations will not display this command.
```ts
when: () => {
const selection = ztoolkit.Reader.getSelectedText(
Zotero.Reader.getByTabID(Zotero_Tabs.selectedID)
);
const sl = …
```
=> Add：Translate sentence by sentence

addon/chrome/content/preferences.xhtml, addon/chrome/locale/en-US/addon.properties, addon/chrome/locale/en-US/overlay.dtd, addon/chrome/locale/zh-CN/addon.properties, addon/chrome/locale/zh-CN/overlay.dtd, addon/prefs.js, src/modules/services.ts, src/modules/services/gpt.ts, src/utils/gptModels.ts
涉及问题： #419 
涉及问题：  
* #405 
* #411  
* #415
**注意**：
* 尽量保证仅包含一个字符，且该字符在原文中不存在，推荐[各种各样的emoji](https://unicode.org/emoji/charts/full-emoji-list.html)
* 不要使用保留字符，例如`$`、`/`、`\`、`?`等
* 支持留空，表示不添加任何字符
* **测试文件**下载：[zotero-pdf-translate.zip](https://github.com/windingwind/zotero-pdf-translate/files/11124817/zotero-pdf-translate.zip)
=> feat: support custom gpt api url and custom special matching char

addon/chrome/content/preferences.xhtml, addon/chrome/locale/en-US/overlay.dtd, addon/chrome/locale/zh-CN/overlay.dtd, src/modules/popup.ts, src/modules/reader.ts
1. Now, users can use button and panel to use translation, and the pop-up textarea becomes an option.
2. Fixing the issue of triggering translation when no text is selected. 
#422
#390 (Maybe)
=> feat: add button to hide popup textarea and fix #422

src/modules/services/cnki.ts
#494 
固定的模板替换，去掉了 cnki 翻译末尾的广告。相关细节见 #494
=> Update cnki.ts, 去掉末尾的广告

addon/prefs.js, src/modules/services/gpt.ts
`eval()` is slower than the alternatives, and it is also unsafe. Using template string instead to avoid `eval()` calls.
reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!
=> refactor: use `replaceAll()` instead of `eval()`

.husky/pre-commit, .lintstagedrc.json, package.json
We have [setup pre-commit hook to format documents before commit for mdn/translated-content](https://github.com/mdn/translated-content/pull/8181). It might be a good idea to do the same thing in this project.
=> chore: add pre-commit hook to format files before commit

src/modules/services/microsoft.ts
Fixes: #510
I believe that the http client of Zotero would set the correct content-length header. And this is [a forbidden header](https://developer.mozilla.org/docs/Glossary/Forbidden_header_name), which means that the programmer should not explicitly set this (the user agent would set this correctly).
For the issue mentioned in #510, it could not translate from Chinere to English. And the status code returned is 400. So this might be due to setting of wrong Content-Length and zotero does not implicitly reject the setting. For unicode other than ascii, the string length is not equal to the content-length. Which has made this error.
Resolving this by removing `Content-Length` header.
Documentation: https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-reference …
=> fix(service/microsoft): remove the explicitly specified content-length

src/modules/services/aliyun.ts, src/modules/services/tencent.ts
Fixes: #566
Reference:
- https://help.aliyun.com/zh/sdk/product-overview/rpc-mechanism#sectiondiv-6jf-89b-wfa
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#encoding_for_rfc3986
=> fix: use RFC3986 URL component format to encode body

src/modules/services/deeplx.ts
在 Deepl 的编码过程中通过计算翻译内容中的 i 的数量来防止被简单的重放攻击。
然而之前提交的计算方式直接将翻译内容中的 i 为 0 的情况 return 了，这导致如果请求翻译的内容不包含 i 字母，则翻译过程被终止无法请求。
=> fix: deeplx ICounts calculation mistake

package.json
=> replace ^ with ~ to avoid using newest version of dependency. limit the zotero-plugin-toolkit version

addon/chrome/locale/en-US/addon.properties, addon/chrome/locale/zh-CN/addon.properties, src/utils/gptModels.ts
类似issue #585，插件的zotero 6版本无法支持输入模型名来支持不同提供商的模型。
感觉与其手动添加不同模型支持，不如像手动填写url一样，手动填写模型名了。毕竟除了很多模型本身支持openai style api，也有各种api转发的开源工具。
=> change model selection to input for custom model supports

addon/prefs.js, src/modules/services/gemini.ts
#805 
顺便，我感觉支持GPT API的代码里的data.result = result.replace(/^\n\n/, "");是没必要的？SSE用"data: "分割之后确实带\n\n，但是这会被JSON.parse忽略。
Gemini API每一个chunk都会有`"finishReason": "STOP"`，所以不能用这个判断停止。
Gemini API不会以`data: [DONE]`结束，所以只需要特判split("data: ")之后第一个是空串。
顺便，GPT API应该用`data: [DONE]`判断结束，而不是finish_reason非null。
=> 支持Gemini流式回复

addon/chrome/locale/en-US/addon.properties, addon/chrome/locale/zh-CN/addon.properties, addon/prefs.js, src/modules/services/gpt.ts, src/utils/gptModels.ts
完善zotero6分支的GPT对gemini模型的支持。  
zotero6分支的虽然可以用one-hub或one-api等中转层，以在GPT配置项使用gemini模型，但还需要zotero-pdf-translate进行类似于 #806 #985 的修改
对应issue #756
=> feat: add stream output select for gemini

src/modules/services/haicidict.ts, tsconfig.json
Changes:
- replace the schema from `http://` to `https://` for security
- Using `DOMParser` to parse the dom, which makes the logic of obtaining information clearer
- Redesign the UI, the information about audio is now been shown in the popups. Check the screenshot below:
=> refactor(service/haicidict): using DOMParser to get the information

addon/prefs.js, eslint.config.mjs, package.json, src/elements/base.ts, src/hooks.ts, src/index.ts, src/modules/fields.ts, src/modules/menu.ts, src/modules/popup.ts, src/modules/prompt.ts, src/modules/services/baidu.ts, src/modules/services/baidufield.ts, src/modules/services/google.ts, src/modules/services/webliodict.ts, src/modules/settings/niutrans.ts, src/modules/shortcuts.ts, src/modules/tabpanel.ts, src/utils/config.ts, src/utils/task.ts, tsconfig.json, typings/global.d.ts
Migrate the configuration of eslint to v9.x. Check: https://eslint.org/docs/latest/use/migrate-to-9.0.0
Run `npm run lint` to check the migration.
=> chore(eslint): migrate to v9.x

src/modules/menu.ts, src/modules/services/youdaodict.ts
- Resolve: https://github.com/windingwind/zotero-better-notes/issues/1082#issuecomment-2306802546
- Do not add the menu separator line when both of the Item Menu checkboxes (ltem Menu: Show Title Translation, ltem Menu: Show Abstract Translation) are unchecked.
=> fix: odd menu separator even if disable item menu settings

src/modules/popup.ts
- Do not show the `Add To Note` button in the translation popup once `Show 'Add Translation to Note' in Popup` is unchecked.
- Fixes: https://github.com/windingwind/zotero-pdf-translate/issues/1046
=> fix: show AddToNote in pupop even if unchecked (#1046)

addon/chrome/content/preferences.xhtml
Fixes: The links in the About panel are unclickable.
And add a blank between the two links.
=> fix: abnormal link in preference panel

addon/locale/en-US/addon.ftl, addon/locale/it-IT/addon.ftl, addon/locale/zh-CN/addon.ftl, addon/prefs.js, src/modules/services/aliyun.ts, src/modules/settings/aliyun.ts, src/modules/settings/index.ts, typings/prefs.d.ts
增加对阿里云的机器翻译专业版支持
添加了对话框来对普通版和专业版的参数选择
文档：https://help.aliyun.com/zh/machine-translation/developer-reference/api-overview-1
这里文档中对专业版和普通版使用`action`区分，英文我就采用action了，中文用的是`版本`，不知道这样行不行
=> add: support aliyun professional edition service (#1124)

addon/chrome/content/preferences.xhtml, addon/locale/en-US/panel.ftl, addon/locale/en-US/preferences.ftl, addon/locale/it-IT/panel.ftl, addon/locale/it-IT/preferences.ftl, addon/locale/zh-CN/panel.ftl, addon/locale/zh-CN/preferences.ftl, addon/prefs.js, src/utils/task.ts, typings/prefs.d.ts
- re: #1134 ，经测试，不勾选Auto-Trans: Selection时，选择同一页不连续的内容按下`Ctrl`+`T`翻译时，会自动激活拼接模式。
- 考虑可以增加Ctrl激活拼接模式的选项（因为Item Pane Section面板的空间有限，选择放在设置面板）
1. 勾选Ctrl激活拼接模式且使用自动翻译Selection时，按住Ctrl选择内容即可拼接（和当前体验相同）
2. 如果使用者习惯`Ctrl`+`T`翻译Selection内容，可以选择不勾选Ctrl激活拼接模式，如果需要拼接时，可以在Info面板选中Concat Mode使用拼接模式翻译
BTW，调整了设置面板的Item Pane Section设置项顺序，和翻译插件在Item Pane Section自上而下组件的顺序一致。
=> feat: add setting for contactKey Ctrl, fixes #1134

addon/locale/en-US/preferences.ftl, addon/locale/it-IT/preferences.ftl, addon/locale/zh-CN/preferences.ftl, src/modules/preferenceWindow.ts
- 将添加到笔记时替换原始文本修改为添加翻译至笔记时替换原始文本，和Pop-up的button内容一致, after [c8ef807](https://github.com/windingwind/zotero-pdf-translate/commit/c8ef807080d6ad00a158bbceb58eeadf72b1e57c)
- 修复在Use Word service保持勾选时，auto-play仅在取消勾选Show Play Buttons in Pop-up Panel后短暂hidden，再次打开设置面板仍然可见, re #1149
=> update locale string and fix broken hidden status for auto-play

addon/prefs.js, typings/prefs.d.ts
This pull request adds new preferences for configuring the Claude translation model in the `addon/prefs.js` file. These changes introduce settings for the model's endpoint, parameters, and prompt structure.
* Added a new preference for enabling streaming responses with the key `__prefsPrefix__.claude.stream`.
* Defined the endpoint for the Claude API using the key `__prefsPrefix__.claude.endPoint`.
* Configured the model version to `claude-3-7-sonnet-20250219` with the key `__prefsPrefix__.claude.model`.
* Introduced a preference for temperature control (`__prefsPrefix__.claude.temperature`) and set it to `0.3` for deterministic results.
* Added a detailed prompt structure for academic translation tasks under the key `__prefsPrefix__.claude.prompt`. This ensures precise translations while …
=> feat: add default values for Claude

src/modules/settings/niutrans.ts
This pull request enhances the functionality and security of the `niutransLogin` process by introducing session management via `JSESSIONID` and improving the handling of API requests. The changes primarily focus on adding session-based authentication and ensuring proper use of headers for subsequent API calls.
* Extracted `JSESSIONID` from the response headers of the `getPublicKey` request and included it in subsequent API calls for session-based authentication. (`src/modules/settings/niutrans.ts`, [src/modules/settings/niutrans.tsL328-R400](diffhunk://#diff-e09db0599ce03a1dfe6258e5aa9eddb712a9309087d4734c59f5e2689df8dfb5L328-R400))
* Modified `loginApi`, `setDictLibList`, and `setMemoryLibList` functions to include the `JSESSIONID` in the `Cookie` header for better session handling. …
=> fix: #1146 zotero-beta-login-failure

addon/locale/en-US/addon.ftl, addon/locale/en-US/panel.ftl, addon/locale/it-IT/addon.ftl, addon/locale/it-IT/panel.ftl, addon/locale/zh-CN/addon.ftl, addon/locale/zh-CN/panel.ftl, addon/prefs.js, src/modules/services/index.ts, src/modules/services/libretranslate.ts, src/modules/settings/index.ts, src/modules/settings/libretranslate.ts, src/utils/config.ts, typings/prefs.d.ts
lint is applied. 
This pull request introduces support for the LibreTranslate translation service, including its integration into the system, configuration options, and localization. Below are the key changes grouped by theme:
* Added LibreTranslate-related strings in `addon/locale/en-US/addon.ftl`, `addon/locale/it-IT/addon.ftl`, and `addon/locale/zh-CN/addon.ftl` to support English, Italian, and Simplified Chinese. These include labels for configuration dialogs and API endpoints. [[1]](diffhunk://#diff-a423c4e18e0c11b4618780c0215b01af0cda2624de66ab598cd2f89774401e1bR158-R168) [[2]](diffhunk://#diff-f7f0504861a799b96445ddd1f2390a9683cc5aba9846c283af8a62471004bcacR132-R140) [[3]](diffhunk://#diff-56144515f3378bd259fd4ff20ab6457a00750b2d557f8f8bc84bb816605be0e2R157-R165)
* Updated …
=> feat: add LibreTranslate service integration and configuration options (#944)

addon/chrome/content/preferences.xhtml, addon/locale/en-US/preferences.ftl, addon/locale/it-IT/preferences.ftl, addon/locale/zh-CN/preferences.ftl, addon/prefs.js, src/modules/services/index.ts, src/utils/str.ts, typings/prefs.d.ts
This pull request introduces a new feature to strip empty lines from translation results, along with supporting changes to integrate this functionality into the application. The most important changes include the addition of a new preference, updates to the user interface, localization support, and the implementation of the core functionality for stripping empty lines.
* Added a new preference `stripEmptyLines` with a default value of `false` in `addon/prefs.js`.
* Updated `preferences.xhtml` to include a new checkbox in the advanced preferences section, allowing users to enable or disable the "Strip empty lines" feature.
* Added localized labels for the "Strip empty lines" preference in English (`en-US`), Italian (`it-IT`), and Simplified Chinese (`zh-CN`) in their respective …
=>  feat: remove newline from llm response (#1156)

addon/locale/en-US/preferences.ftl, addon/locale/it-IT/preferences.ftl, addon/locale/zh-CN/preferences.ftl, src/utils/str.ts, typings/i10n.d.ts
Similar to Release v2.2.6 (https://github.com/windingwind/zotero-pdf-translate/commit/b29645f42ce8b3dadc9908151099888f3c0f090f), this PR helps people does not know how to use Regex and just simply get rid of thinking tag.
This pull request introduces changes to enhance the handling of translation results by stripping both empty lines and "thinking" tags from text. Updates include modifications to localization files for multiple languages and improvements to the `stripEmptyLines` function in the codebase.
* [`addon/locale/en-US/preferences.ftl`](diffhunk://#diff-8b21f73c3b3b782dff21e947b73d8dd2dde9553b53d7d7efbebd451dddc368afL119-R119): Updated the label for `pref-advanced-stripEmptyLines` to clarify that both empty lines and thinking content are stripped from translation results.
* …
=> fix: update translation labels to include stripping 'thinking' context

src/modules/prompt.ts
To support dark mode
- Before this PR
- After this PR
=> fix: bg color for SentenceBySentence Translation

src/modules/settings/gpt.ts
To support dark mode.
In addition, the `Add Parameter` button is ineffective for me. Could you take a look when you have a moment? @Chapoly1305
=> fix: bg color for custom parameters setting, after #1226

README.md, addon/chrome/content/preferences.xhtml, addon/prefs.js, src/modules/defaultPrefs.ts, src/modules/services/deeplcustom.ts, src/modules/services/mtranserver.ts, src/modules/settings/deeplcustom.ts
- Before v2.2.22, the EndPoint has been set in the Secret input box. 2.2.22 version changes it to Config-EndPoint to be unified with other 📍services. However, this may affect the user experience of some old users (manual changes are required when using a non-`http://127.0.0.1:8080/translate` API URL). This PR fixes it.
- Change the help documentation for DeepLX(API) and add the guide for another available DeepLX-related service.
=> fix: incompatible with old DeepLX(API) settings

src/utils/config.ts
- Clean the secretValidator code for the 📍 services that need no secret. Sort the code block.
- Add a hint for the default secret of the Caiyun service.
=> fix: modify secret validator and clean code

README.md, src/modules/popup.ts, src/utils/task.ts
- Resolve https://github.com/windingwind/zotero-pdf-translate/pull/1264#discussion_r2259646726
**Disable Auto-Trans Selection** and **Enable concat mode**
The previous scheme results in a persistent Translate button and a hidden pop-up text area.
---
- Another issue
- If we highlighted an annotation and auto-trans it with the concat mode enabled. Then, select some new text, and the annotation translation result will be displayed in the pop-up rather than the Translate button. Triggering` Ctrl/Cmd+T` or clicking the Translate button in the item pane will re-translate the annotation.
**Actually, it might be the wrong way to use the concat mode (highlight annotation and auto-trans with enabled concat mode)**, so I think it is ok to keep it there.
=> fix: pop-up ui with enabled concat mode

src/modules/defaultPrefs.ts
The previous default-free service, Haici, is no longer available.
Re https://github.com/windingwind/zotero-pdf-translate/issues/1202, https://github.com/windingwind/zotero-pdf-translate/issues/1221#issuecomment-3063456710
=> chore: set CNKI as default service for China mainland

src/modules/services/gpt.ts, src/utils/settingsDialog.ts
- The toolkit does not automatically infer boolean from input>checkbox, so it needs to be specified manually.
- The prompt is missing `()`, causing the order to be incorrect.
=> fix: gpt service error since settings refactor introduced pref type issue

README.md, src/modules/services/microsoft.ts
Now, new users can't choose the Global region when registering a new Microsoft secret. Resolve https://github.com/windingwind/zotero-pdf-translate/issues/950#issuecomment-2513766014
=> docs: add hint for the region in Microsoft secret
